[build]
command = "bun run build"
publish = "dist"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/ex-caller/*"
to = "/2025-04-11/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://github.com/typed-sigterm/talks"
status = 302
