[build]
command = "bun run build"
publish = "dist"

[[redirects]]
from = "/ex-caller/*"
to = "/ex-caller/index.html"
status = 200

[[redirects]]
from = "/techs-in-junior/*"
to = "/techs-in-junior/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://github.com/typed-sigterm/talks"
status = 301
